### ISSUE TITLE
Performance metrics

### ISSUE THREAD

**Issue by anderseknert** [johanfylling/jarl#54]
In order to know where we have bottlenecks, and to know if we have regressions over time, it would be nice to provide performance metrics, covering at least:

* Provide equivalent flag to `opa eval --metrics`: `timer_rego_query_eval_ns` and `timer_rego_query_parse_ns`
* Java / clojure function call "heat graph"
* Wall clock time
* Memory / CPU usage

In order to catch performance regressions, we should add a task to the build which captures performance metrics and report the outcome.

**Comment by johanfylling** [comment]
https://github.com/hugoduncan/criterium
