### ISSUE TITLE
Provide logging framework that works across platforms

### ISSUE THREAD

**Issue by anderseknert** [johanfylling/jarl#64]
While the clojure.tools.logging library provides basic logging functionality (and that's likely all we'll need for now), the [timbe](https://github.com/ptaoussanis/timbre) project seems like a great modern, well-maintained, alternative. 

What makes it particularly interesting to me is that it works the same for both Clojure and Clojurescript, leading to way less differences in code between the two, which will be imperative for #53

**Comment by johanfylling** [comment]
Worthwhile to look into.
Considering the prime use for Jarl will likely be as a library in other JVM apps, an important aspect to consider is outbound interop with common logging frameworks for java, which `org.clojure/tools.logging` does pretty well. If this is also possible with timbre, I see no reason for not changing.

**Comment by anderseknert** [comment]
Fair point. I wonder how I'd test that? 🤔

**Comment by anderseknert** [comment]
Seems to be possible via a plugin https://github.com/palletops/log-config#timbre-and-java-logging
Or even natively to use tools.logging via timbre (although they don't recommend it) https://ptaoussanis.github.io/timbre/taoensso.timbre.tools.logging.html

Perhaps we could set the log configuration depending on the "build target", or something as such.

**Comment by anderseknert** [comment]
[This](https://lambdaisland.com/blog/2020-06-12-logging-in-clojure-making-sense-of-the-mess) was a pretty good summary of the alternatives. Timbre seems like the strongest contender still, so will start with that.

**Comment by johanfylling** [comment]
Alright! So the logging chain for the JVM would be something like `timbre`->`tools.logging`->`slf4j`/`log4j`/`java.util.logging`/etc.?

**Comment by anderseknert** [comment]
Not necessarily for everything JVM. One thing I will want to look into is involving components other than timbre only when the Java API is built, or a client asks for it. But yeah, pretty much.

**Comment by johanfylling** [comment]
Yes, a pure clojure app wouldn't need to bridge to `tools.logging`, and further 👍 .
